export const countryCodes = [
    { code: '57', name: 'Colombia', flag: '🇨🇴' },
    { code: '1', name: 'Estados Unidos', flag: '🇺🇸' },
    { code: '34', name: 'España', flag: '🇪🇸' },
    { code: '52', name: 'México', flag: '🇲🇽' },
    { code: '54', name: 'Argentina', flag: '🇦🇷' },
    { code: '56', name: 'Chile', flag: '🇨🇱' },
    { code: '51', name: 'Perú', flag: '🇵🇪' },
    { code: '593', name: 'Ecuador', flag: '🇪🇨' },
    { code: '58', name: 'Venezuela', flag: '🇻🇪' },
    { code: '507', name: 'Panamá', flag: '🇵🇦' },
    { code: '506', name: 'Costa Rica', flag: '🇨🇷' },
    { code: '503', name: 'El Salvador', flag: '🇸🇻' },
    { code: '502', name: 'Guatemala', flag: '🇬🇹' },
    { code: '504', name: 'Honduras', flag: '🇭🇳' },
    { code: '591', name: 'Bolivia', flag: '🇧🇴' },
    { code: '595', name: 'Paraguay', flag: '🇵🇾' },
    { code: '598', name: 'Uruguay', flag: '🇺🇾' },
    { code: '809', name: 'Rep. Dominicana', flag: '🇩🇴' },
    { code: '55', name: 'Brasil', flag: '🇧🇷' },
    { code: '44', name: 'Reino Unido', flag: '🇬🇧' },
    { code: '33', name: 'Francia', flag: '🇫🇷' },
    { code: '39', name: 'Italia', flag: '🇮🇹' },
    { code: '49', name: 'Alemania', flag: '🇩🇪' },
    { code: '86', name: 'China', flag: '🇨🇳' },
    { code: '81', name: 'Japón', flag: '🇯🇵' },
    { code: '91', name: 'India', flag: '🇮🇳' },
    { code: '61', name: 'Australia', flag: '🇦🇺' },
    { code: '1', name: 'Canadá', flag: '🇨🇦' },
];
