export const COMMON_LOTTERIES = [
    "Chontico Día",
    "Chontico Noche",
    "Paisita Día",
    "Paisita Noche",
    "Lotería de Bogotá",
    "Lotería de Medellín",
    "Lotería de Boyacá",
    "Lotería del Valle",
    "Lotería de Cundinamarca",
    "Lotería del Tolima",
    "Lotería del Huila",
    "Lotería del Meta",
    "Lotería de Manizales",
    "Lotería del Cauca",
    "Lotería de Santander",
    "Lotería del Risaralda",
    "Lotería del Quindío",
    "Lotería de la Cruz Roja",
    "Pijao de Oro",
    "Culona Día",
    "Culona Noche",
    "Sinuano Día",
    "Sinuano Noche",
    "Caribeña Día",
    "Caribeña Noche",
    "Astro Sol",
    "Astro Luna",
    "Dorado Mañana",
    "Dorado Tarde"
];
